@echo off
echo Starting deployment process...

echo Installing dependencies...
call npm install

echo Building for production...
call npm run production:build

echo Starting production server...
set PORT=3000
call npm run production:start 